[package]
name = "marin"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
codespan-reporting = "0.11.1"
colored = "3.0.0"
either = "1.13.0"
logos = "0.14.2"
petgraph = "0.6.5"

[build-dependencies]
build-print = "0.1.1"
fs_extra = "1.3.0"
